CREATE TABLE tale (
  hash BIGINT UNSIGNED,
  digit1 TINYINT UNSIGNED,
  digit2 TINYINT UNSIGNED,
  digit3 TINYINT UNSIGNED,
  digit4 TINYINT UNSIGNED,
  digit5 TINYINT UNSIGNED,
  pb TINYINT UNSIGNED,
  count BIGINT UNSIGNED,
  dayCount INT UNSIGNED,
  weekCount INT UNSIGNED,
  monthCount INT UNSIGNED,
  yearCount INT UNSIGNED,
  time DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (hash),
  INDEX (count),
  INDEX (dayCount),
  INDEX (weekCount),
  INDEX (monthCount),
  INDEX (yearCount),
  INDEX (digit1),
  INDEX (digit2),
  INDEX (digit3),
  INDEX (digit4),
  INDEX (digit5),
  INDEX (pb),
  INDEX (time, hash)
);

CREATE TABLE history (
  hash BIGINT UNSIGNED,
  digit1 TINYINT UNSIGNED,
  digit2 TINYINT UNSIGNED,
  digit3 TINYINT UNSIGNED,
  digit4 TINYINT UNSIGNED,
  digit5 TINYINT UNSIGNED,
  pb TINYINT UNSIGNED,
  time DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (hash),
  INDEX (digit1),
  INDEX (digit2),
  INDEX (digit3),
  INDEX (digit4),
  INDEX (digit5),
  INDEX (pb),
  INDEX (time)
);
